# General
name: Drvy's Blog
description: "Desarrollo web y otras cosas..."
url: https://blog.drvy.net

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: drvy
twitter: drvymonkey
github: drvy
google: +DrvyMonkey

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"